service: gateway

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

  apiKeys:
    - test-key

  iamRoleStatements:
    # for serverless-plugin-warmup
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - Fn::Join:
            - ":"
            - - arn:aws:lambda
              - Ref: AWS::Region
              - Ref: AWS::AccountId
package:
  exclude:
    - .idea/**
    - node_modules/**
    - .github/**

functions:
  status:
    handler: src/status.get
    events:
      - http:
          path: status
          method: get
          private: false
          cors: true
